name: Create PR with Hourly Cron Job

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  test-name:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update Changelog
        run: |
          now=$(date +'%Y-%m-%d')  # Generate date only (without time)
          curl "http://worldtimeapi.org/api/timezone/Europe/London" > "webpage_$now"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: update changelog
          title: Update Changelog
          body: Update changelog to reflect release changes
          branch: update-changelog
          base: main